CREATE TABLE IF NOT EXISTS AGER_TRENES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero VARCHAR(80) NOT NULL UNIQUE,
    origen VARCHAR(120) NOT NULL,
    destino VARCHAR(120) NOT NULL,
    empresa VARCHAR(120) NOT NULL,
    fecha DATE NOT NULL,
    estatus VARCHAR(120) NOT NULL,
    situacion VARCHAR(120) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
